# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 03:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '4')])),
                ('comment', models.CharField(max_length=1024)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='rating',
            name='movieId',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='userId',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
