# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-31 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20161029_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedmovielist',
            name='algo',
            field=models.CharField(choices=[('KMEAN', 'KMEAN')], default='KMEAN', max_length=128),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterUniqueTogether(
            name='recommendedmovielist',
            unique_together=set([('user', 'movie', 'algo')]),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('user', 'movie')]),
        ),
    ]
