# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20161030_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedmovielist',
            name='algo',
            field=models.CharField(default='NAIVE', max_length=128),
        ),
    ]
